name: Dishant Meena

on: push

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - name: Find and Replace

        uses: jacobtomlinson/gha-find-replace@master

        with:

          find: "https://telegra.ph/file/cee753391111580ae8a0c.jpg"

          replace: "https://telegra.ph/file/44a89dae5c134fdcd8203.jpg"

      - name: Create Pull Request

        uses: stefanzweifel/git-auto-commit-action@v4

        with:

          commit_message: 'Replaced new name'

          commit_options: '--no-verify'

          repository: .

          commit_user_name: MickeyxD

          commit_user_email: dishantmeena456@gmail.com
